### ISSUE TITLE
set values from cloudprovider backends SecretManager, ParameterStore ...

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/provider-helm#116]
### What problem are you facing?

set secrets from cloudprovider backends like AWS SecretManager, ParameterStore
### How could Crossplane help solve your problem?

we could implement https://github.com/variantdev/vals and can configure values like:

```
            set: 
              - name: token
                valueFrom: 
                  valRef: 
                    key: ref+awssecrets://myteam/mydoc#/foo/bar
```

We need to add authentication to provider-helm to grant access in CloudProvider
