### ISSUE TITLE
secretKeyRef overwrites key name

### ISSUE THREAD

**Issue by stewartshea** [crossplane-contrib/provider-helm#118]
### What happened?
Scenario: I'm using the provider-helm as a workaround (until https://github.com/crossplane-contrib/provider-kubernetes/pull/21 is merged) to create a secret on a remote cluster. This secret is intended for use by flux, and takes in the `flux-sync` data keys as inputs to a very basic helm chart. Unfortunately, the key fields aren't being honored in the helm template, and instead, the valueFrom reference appears to overwrite the key name. This is a problem when the key name needs to be "identity.pub", but that type of naming is not possible (as far as I know) when setting the helm values (as it would assume that `.pub` is a child value of `identity`). 

### How can we reproduce it?
- Sample helm chart template: 
```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ .Values.secret.name }}
  namespace:  {{ .Values.secret.namespace }}
type: Opaque
data:
  identity: {{ .Values.secret.data.identity | toString | b64enc | quote }}
  identity.pub: {{ .Values.secret.data.identity_pub | toString | b64enc | quote }}
  known_hosts: {{ .Values.secret.data.known_hosts | toString | b64enc | quote }}
```
- Sample values.yaml
```
secret:
  name: "secret"
  namespace: "default"
  data:
    identity: ""
    identity_pub: ""
    known_hosts: ""
```
Sample Crossplane Helm Resource
```
---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: secret-only
spec:
# rollbackLimit: 3
  forProvider:
    chart:
      name: secret-only
      repository: https://stewartshea.github.io/helm-charts/
    namespace: flux-system
    values:
      secret: 
        name: flux-sync
        namespace: flux-system 
    set: 
    - name: secret.data.identity
      valueFrom:     
        secretKeyRef:
          name: flux-sync
          namespace: flux-system
          key: identity
    - name: secret.data.identity_pub
      valueFrom:     
        secretKeyRef:
          name: flux-sync
          namespace: flux-system
          key: identity.pub  
    - name: secret.data.known_hosts
      valueFrom:     
        secretKeyRef:
          name: flux-sync
          namespace: flux-system
          key: known_hosts   
  providerConfigRef:
    name: providerconfig-helm
```

The above combination *will* create the secret on the remote cluster, but with a key titled *identity_pub* instead of "identity.pub" as specified by the helm chart. This could very well be a mistake on my end as I've not had to author a helm chart before but after quite a bit of testing it feels like crossplane-helm is just overwriting the key. I've changed the name from `secret.data.identity_pub` to other names, and indeed the key always matches what is in that field. 

### What environment did it happen in?
Crossplane version: 
- crossplane-1.6.1 
- crossplane/provider-helm:v0.9.0
- GKE - v1.21.5-gke.1302

**Comment by jonasz-lasut** [comment]
Hi @stewartshea, thank you for opening the issue, and apologies that it sat unanswered this long — we're working through the backlog.

Good news first: this is not a provider bug, and what you were trying to do is possible — it just needs Helm's dot-escape syntax (verified below).

## Root cause — confirmed (code, v0.9.0 → current main)

`set[].valueFrom.secretKeyRef.key` only selects **which key of the source secret to read the value from** ([`getDataValueFromSource`](https://github.com/crossplane-contrib/provider-helm/blob/v0.9.0/pkg/controller/release/data.go#L66-L84)). It never names anything in the rendered manifest. The path the value lands on in the Helm values is governed entirely by `set[].name`, which is applied with exact `helm --set` semantics via `strvals.ParseInto` — [`values.go#L83` at v0.9.0](https://github.com/crossplane-contrib/provider-helm/blob/v0.9.0/pkg/controller/release/values.go#L83), byte-identical on [current main](https://github.com/crossplane-contrib/provider-helm/blob/81971d7acff0/pkg/controller/cluster/release/values.go#L83).

So in your manifest, `key: identity.pub` *was* honored — the correct data was read from the `flux-sync` secret — but it landed on the values path `secret.data.identity_pub`, because that is what `name:` says. In `--set` syntax an unescaped `.` always means nesting, which is why every rename of `name:` tracked straight into the key you observed.

## Reproduced (standalone repro of `composeValuesFromSpec` + helm engine render)

Composing values exactly as the provider does with your three `set` entries yields:

```yaml
secret:
  data:
    identity: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      <redacted>
    identity_pub: |
      ssh-ed25519 <redacted> flux
    known_hosts: github.com ssh-rsa <redacted>
  name: flux-sync
  namespace: flux-system
```

Rendering the template **as pasted in this issue** (hardcoded `identity.pub:` key) against these values produces a correct Secret with the `identity.pub` key — the pasted template cannot produce the symptom you saw. A template that instead does `{{ range $key, $value := .Values.secret.data }}` reproduces it exactly (output key `identity_pub`), because there the manifest keys come from the values map, i.e. from `set[].name`. Your chart repo is no longer published so I couldn't check the deployed template, but the range shape is the only one consistent with what you observed.

## Workaround — verified working

Escape the dot in `set[].name`, exactly as you would with `helm --set`:

```yaml
set:
- name: secret.data.identity\.pub
  valueFrom:
    secretKeyRef:
      name: flux-sync
      namespace: flux-system
      key: identity.pub
```

This produces `secret: {data: {"identity.pub": ...}}` in the values map, and the rendered Secret carries the `identity.pub` key. Verified against the unmodified provider code path — works on v0.9.0 through current main.

## Caveat — `set` values ride the typed `--set` parser

One thing to be aware of with secret-sourced `set` values: a value containing a comma (e.g. a multi-host `known_hosts` line `github.com,140.82.121.4 ssh-ed25519 ...`) fails reconciliation with `failed parsing --set data: key "..." has no value`, and bare `true`/`null` values are coerced to bool/null rather than kept as strings. Multiline values (SSH private keys) pass through fine. If the comma case bites you, comment here and we'll track a `--set-literal`-style mode as a separate feature.

Closing as working-as-designed. If the escape syntax doesn't resolve it for your case, please comment and we'll reopen.
