### ISSUE TITLE
Cannot get connection details: object is not part of release

### ISSUE THREAD

**Issue by huaxk** [crossplane-contrib/provider-helm#148]
### What happened?
I tried to expose one of the secret fields in connectionDetails, but got warning: cannot get connection details:

 `cannot get connection details: object is not part of release: {Secret test vc-vcluster-test v1 data.config}` 

because reason: 

`CannotObserveExternalResource`

But I found out that the secret named vc-vcluster-test exists in namespace test.

### How can we reproduce it?
Apply this file to crossplane with a verified secret named vc-vcluster-test exists in namespace test:

```
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: vcluster-test
  annotations:
    crossplane.io/external-name: vcluster-test
spec:
  connectionDetails:
    - apiVersion: v1
      kind: Secret
      name: vc-vcluster-test
      namespace: test
      fieldPath: data.config
      toConnectionSecretKey: kubeconfig
  writeConnectionSecretToRef:
    name: vcluster-test-secret
    namespace: crossplane-system
  rollbackLimit: 3
  providerConfigRef:
    name: helm-provider
  forProvider:
    namespace: test
    chart:
      name: vcluster
      repository: https://charts.loft.sh
      version: "0.12.2"
```

### What environment did it happen in?

* Crossplane version: crossplane-1.9.1
* Kubernetes version: v1.21.11
* Kubernetes distribution: rke2r1
* provider-helm: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.12.0
* Kernel :Linux harvester1 5.3.18-150300.59.63-default #1 SMP Tue Apr 5 12:47:31 UTC 2022 (d77db66) x86_64 x86_64 x86_64 GNU/Linux
