### ISSUE TITLE
Integrate kubelogin for Azure AD Authentication to AKS Clusters

### ISSUE THREAD

**Issue by marianheinsen** [crossplane-contrib/provider-helm#180]
### What problem are you facing?
We are provisioning Azure AKS Kubernetes Clusters using the [Azure Provider by Upbound](https://marketplace.upbound.io/providers/upbound/provider-azure/). After provisioning, we install software inside of the clusters using this Helm Provider as well as the related [Kubernetes Provider](https://github.com/crossplane-contrib/provider-kubernetes). When using Local Accounts for authentication with the clusters API servers, this works out of the box. However, we would like to switch to authentication based on Azure AD Service Principals and Managed Identities, as this is the best practice and recommended by Azure. The [Kubernetes Go Client](k8s.io/client-go) which is used by this provider does not support this authentication method by default, so currently we can't use this provider with AKS clusters configured with Azure AD Authentication. As the same problem arises with standard kubectl usage and Terraform providers as well (see e.g. https://github.com/Azure/kubelogin/issues/114), Azure provides the [kubelogin](https://github.com/Azure/kubelogin) client-go credential plugin which can be used to retrieve the user credentials and pass it to the Kubernetes Go Client.

### How could Crossplane help solve your problem?
I propose to integrate the [official kubelogin Go package](https://pkg.go.dev/github.com/Azure/kubelogin) into this provider (as well as the Kubernetes Provider), so that it's possible to use it with AKS clusters configured with Azure AD Authentication. I'm open to provide an implementation for this and open a PR. Also, I would be happy to hear the maintainer's thoughts about this. Are you open to such contribution? @turkenh @negz

**Comment by marianheinsen** [comment]
Related issue in Kubernetes Provider repo: https://github.com/crossplane-contrib/provider-kubernetes/issues/105

**Comment by haarchri** [comment]
I'm encountering the same issue when trying to connect to an AKS cluster with authentication based on Azure AD Service Principals and Managed Identities. The error message indicates that the `kubelogin` executable is not found. 

**Error Details:**
```plaintext
Type     Reason                   Age                 From                                Message
  ----     ------                   ----                ----                                -------
  Warning  CannotConnectToProvider  23m (x10 over 27m)  managed/release.helm.crossplane.io  cannot create new Kubernetes client: cannot create Kubernetes client: Get "https://test123-aks-23c35881-9a9e-4ee3-aef9-2b4cc02d7d00-rq3nt806.hcp.westus.azmk8s.io:443/api?timeout=32s": getting credentials: exec: executable kubelogin not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
      https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

kubelogin is not installed which is required to connect to AAD enabled cluster.

To learn more, please go to https://aka.ms/aks/kubelogin
```

**Provided Kubeconfig:**
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xyz==
    server: https://test123-aks-23c35881-9a9e-4ee3-aef9-2b4cc02d7d00-rq3nt806.hcp.westus.azmk8s.io:443
  name: test123-aks-j5wsb-f2b4q
contexts:
- context:
    cluster: test123-aks-j5wsb-f2b4q
    user: clusterUser_start123-rg_test123-aks-j5wsb-f2b4q
  name: test123-aks-j5wsb-f2b4q
current-context: test123-aks-j5wsb-f2b4q
kind: Config
preferences: {}
users:
- name: clusterUser_start123-rg_test123-aks-j5wsb-f2b4q
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - 6dae42f8-1234-4678-1234-3960e28e3630
      - --client-id
      - 80faf920-1234-4b52-1234-a8e7bedfc67a
      - --tenant-id
      - b9925bc4-1234-4c37-1234-fa456d1bb1c7
      - --login
      - devicecode
      command: kubelogin
      env: null
      installHint: |2
        kubelogin is not installed which is required to connect to AAD enabled cluster.
        To learn more, please go to
        https://aka.ms/aks/kubelogin
```

**Comment by haarchri** [comment]
using the following manifest for kubernetesCluster:

```
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: test123-aks-j5wsb-wdh8r
spec:
  deletionPolicy: Delete
  forProvider:
    apiServerAccessProfile:
    - vnetIntegrationEnabled: true
    autoScalerProfile:
    - emptyBulkDeleteMax: "10"
      expander: random
      maxGracefulTerminationSec: "600"
      maxNodeProvisioningTime: 15m
      maxUnreadyNodes: 3
      maxUnreadyPercentage: 45
      newPodScaleUpDelay: 0s
      scaleDownDelayAfterAdd: 10m
      scaleDownDelayAfterDelete: 10s
      scaleDownDelayAfterFailure: 3m
      scaleDownUnneeded: 10m
      scaleDownUnready: 20m
      scaleDownUtilizationThreshold: "0.5"
      scanInterval: 10s
      skipNodesWithSystemPods: true
    azureActiveDirectoryRoleBasedAccessControl:
    - adminGroupObjectIds:
      - 6f49479a-1234-480b-1234-741b51a973a1
      azureRbacEnabled: true
      managed: true
      tenantId: b9925bc4-1234-4c37-1234-fa456d1bb1c7
    azurePolicyEnabled: true
    defaultNodePool:
    - customCaTrustEnabled: false
      enableAutoScaling: true
      enableHostEncryption: false
      enableNodePublicIp: false
      fipsEnabled: false
      kubeletDiskType: OS
      maxCount: 10
      maxPods: 30
      minCount: 1
      name: nodepool1
      nodeCount: 1
      onlyCriticalAddonsEnabled: false
      orchestratorVersion: 1.27.3
      osDiskSizeGb: 128
      osDiskType: Ephemeral
      osSku: Ubuntu
      scaleDownMode: Delete
      type: VirtualMachineScaleSets
      ultraSsdEnabled: false
      vmSize: Standard_DS3_v2
      workloadRuntime: OCIContainer
    dnsPrefix: test123-aks-d679da55-b462-415e-8b04-7487ac5bbd3d
    identity:
    - identityIds:
      - /subscriptions/038f2b7c-1234-43b8-1234-c9ad5da610a8/resourceGroups/start123-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test123-aks-j5wsb-q46cg
      type: UserAssigned
    imageCleanerIntervalHours: 48
    kubernetesVersion: 1.27.3
    location: westus
    networkProfile:
    - networkPlugin: azure
    nodeResourceGroup: MC_start123-rg_test123-aks-j5wsb-wdh8r_westus
    oidcIssuerEnabled: true
    omsAgent:
    - logAnalyticsWorkspaceId: /subscriptions/038f2b7c-1234-43b8-1234-c9ad5da610a8/resourceGroups/start123-rg/providers/Microsoft.OperationalInsights/workspaces/test123-aks-j5wsb-clzf4
      msiAuthForMonitoringEnabled: true
    publicNetworkAccessEnabled: true
    resourceGroupName: start123-rg
    roleBasedAccessControlEnabled: true
    runCommandEnabled: true
    skuTier: Standard
    tags:
      app: test123
      env: dev
      namespace: start123
    windowsProfile:
    - adminUsername: azureuser
    workloadIdentityEnabled: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: 7867facd-54cd-42ed-8402-bff9af903ba0-akscluster
    namespace: upbound-system
```
