### ISSUE TITLE
Passing args to configure the Helm provider package to configure the controller and be more verbose

### ISSUE THREAD

**Issue by cmoulliard** [crossplane-contrib/provider-helm#190]
### What problem are you facing?

When we use the helm-provider package and we install a helm chart using a release CR
```
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: postgresql
spec:
  forProvider:
    chart:
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 11.9.1
    namespace: db
    skipCreateNamespace: false
    wait: true
    set:
    - name: auth.username
      value: healthy
    - name: auth.password
      value: healthy
    - name: auth.database
      value: fruits_database
  providerConfigRef:
    name: helm-provider
```
the log of the pod running the helm controller is empty 
```
 ~ kubectl logs -n crossplane-system provider-helm-c82775aaeb9c-6fd67d85c8-9sm94
 ~ 
```

and do not show the log generated by helm. Such a text will be displayd if you perform a deployment locally using the helm client:
```
helm upgrade -i postgresql postgresql --repo https://charts.bitnami.com/bitnami
Release "postgresql" does not exist. Installing it now.
NAME: postgresql
LAST DEPLOYED: Tue Apr 25 16:12:00 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: postgresql
CHART VERSION: 12.4.1
APP VERSION: 15.2.0

** Please be patient while the chart is being deployed **

PostgreSQL can be accessed via port 5432 on the following DNS names from within your cluster:

    postgresql.default.svc.cluster.local - Read/Write connection

To get the password for "postgres" run:

    export POSTGRES_PASSWORD=$(kubectl get secret --namespace default postgresql -o jsonpath="{.data.postgres-password}" | base64 -d)
...
```

### How could Crossplane help solve your problem?

That would be nice if we could change the logging level of the Helm provider controller (when we install the package) to be able to configure then the logger of the [command](https://github.com/crossplane-contrib/provider-helm/blob/master/cmd/provider/main.go#L48) and by consequence to be able to display the result of the execution of the helm deploy within the pod log. Even better the result tof the helm deploy should be attached as a status message and used by a UI or the crossplane client to show what it happened
