### ISSUE TITLE
Installation of provider-helm fails with "resource name may not be empty" in air-gapped environment.

### ISSUE THREAD

**Issue by emreyokur** [crossplane-contrib/provider-helm#201]
We have an air-gapped kubernetes environment. 
We followed the installation procedure of crossplane and successfully installed it. However, when we want to install provider-helm, we see the following error in the output of "kubectl describe provider".

```
_Warning UnpackPackage 10m (x24 over 28m) packages/provider.pkg.crossplane.io cannot unpack package: failed to fetch package digest from remote: resource name may not be empty_
```

Since we have an air-gapped environment, we did some manipulations which none worked. 
- We pulled provider-helm-controller image and pushed it to our internal private registry. 
- We forked the provider-helm repository on github. Modified **crossplane.yaml**, added **spec.controller.image** which points to our internal image registry which I have mentioned. 
- We run the pipeline (i.e build provider-helm from scratch - we pushed the resulting image to our personal docker.hub account, then pulled from there and installed it to our internal private registry.)
- Finally, we applied the below yaml to install provider-helm, however the error message did not change.

```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: <our_private_image_registry>/crossplane-contrib/provider-helm:master
  packagePullPolicy: Always
  packagePullSecrets:
    - name: <our_pull_secret>
```

PS:  We have internal registry but we do not use self-signed certificate. We use Digicert Global.

Any clue or help is appreciated.
