### ISSUE TITLE
Unable to pull Charts from Private Registry

### ISSUE THREAD

**Issue by sujith1594** [crossplane-contrib/provider-helm#202]
### What happened?

I'm trying to create a Helm Release using helm-provider, but I'm getting "Certificate Signed by Unknown authority even after adding "insecureSkipTLSVerify: true". Can some one help me how to fix the cert issue or how can I skip the TLS verification?

### How can we reproduce it?

```
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: helm-testing
spec:
  forProvider:
    insecureSkipTLSVerify: true
    chart:
      pullSecretRef:
        name: helm-secret
        namespace: default
      name: <Chart Name>
      repository: oci://<Private Registry>
      version: 0.1.1
    namespace: default
    values:
      cluster_name: crossplane
  providerConfigRef:
    name: default
```

### What environment did it happen in?
Crossplane version:  1.13.2

Include at least the version or commit of Crossplane you were running. Consider
also including your:

* Cloud provider : AWS
* Kubernetes version (use `kubectl version`): 1.25
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift) EKS
* OS (e.g. from /etc/os-release) amzn linux

**Comment by jbw976** [comment]
In terms of the `insecureSkipTLSVerify` option, looks like [support for that](https://github.com/helm/helm/commit/08593c8dd6e4b05b1855296f6d7c6247de1d9e6a) was added to [helm v3.12.0](https://github.com/helm/helm/releases/tag/v3.12.0), and we're currently on v3.10.2 in this repo. So perhaps upgrading our dependency would make `insecureSkipTLSVerify` start working 🤔 

Are you interested in testing that out in your environment? 🙏 

There may be further work to make end to end TLS work, but it's hard to tell what may be wrong there without setting up a specific repro environment that we have full control over - otherwise there's too many unknown variables in the environment for which this issue was opened in.

**Comment by csantanapr** [comment]
Thanks for looking into this @jbw976 

So it looks like `insecureSkipTLSVerify` works with http based helm registry, but never worked when using `oci://` registry

@sujith1594 which registry you are using, is it based on an open source and could you provide how is it setup?

**Comment by sujith1594** [comment]
Hi @csantanapr, We are using Redhat Quay which is built on top of Openshift Cluster. Quay is an OCI Registry

**Comment by cristian98149** [comment]
Hi @sujith1594,

which fiels are set in your secret?

I would like to pull from a private ECR registry but I can't find how the secret must be composed.

Thank you.

BR

**Comment by philippart** [comment]
I've got the same problem with Zot OCI registry:
```
forProvider:
  chart:
    name: scheduler
    pullSecretRef:
      name: ""
      namespace: ""
    repository: oci://zot.default.svc.cluster.local:5000/charts
    version: 0.1.0
  insecureSkipTLSVerify: true
```

The provider-helm Release returns this error:
`Warning  CannotCreateExternalResource  1s (x6 over 10s)  managed/release.helm.crossplane.io  failed to install release: failed to pull chart: failed to do request: Head "https://zot.default.svc.cluster.local:5000/v2/charts/scheduler/manifests/0.1.0": tls: failed to verify certificate: x509: certificate signed by unknown authority`

My certificate has the proper FQDN and SAN but was signed by a self-signed root CA. I'm going to try with the cluster CA.

**Comment by turkenh** [comment]
Looks like helm added a `--plain-http` different than insecure skip tls verify for this kind of scenarios: https://github.com/helm/helm/pull/12128

We would need a corresponding spec in the API type and pass it to our helm clients [here](https://github.com/crossplane-contrib/provider-helm/blob/477dcac827749ed27901d742a1e14e3479e4c21b/pkg/clients/helm/client.go#L115).

Contributions are welcome 🙏

**Comment by stepan111** [comment]
I just want tot share workaround  to make it work with self-hosted zot registry:
```
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-helm
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            env:
             - name: SSL_CERT_FILE
               value: /certs/ca-bundle
            volumeMounts:
            - mountPath: /certs
              name: ca-certs
          volumes:
          - configMap:
              defaultMode: 420
              items:
              - key: ca-bundle
                path: ca-bundle
              name: ca-bundle-config
            name: ca-certs
  serviceAccountTemplate:
    metadata:
      name: provider-helm

```
I made this ca-bundle configmap with steps from here: https://docs.crossplane.io/latest/guides/self-signed-ca-certs/
