### ISSUE TITLE
Rollback feature doesn't work as expected. 

### ISSUE THREAD

**Issue by johnathan-sq** [crossplane-contrib/provider-helm#219]
### What happened?

When I try to rollback a feature the provider will detect that that status is out of sync from Helm and try to update the release to match the deployed state. This ends up resulting in a continuous loop of rollback.

### How can we reproduce it?

1.  (This will succeed)
```
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress-example-4
spec:
  rollbackLimit: 1
  forProvider:
    chart:
      name: generic-deployment
      repository: https://johnathan-sq.github.io/charts/
      version: "0.2.0"
    namespace: wordpress-4
    wait: true
    waitTimeout: 15s
    values:
      replicaCount: 1
      image:
        repository: nginx
        pullPolicy: IfNotPresent
        tag: "latest"
  providerConfigRef:
    name: helm-provider
```
2. (This will break it, note the **nginxx**)
```
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress-example-4
spec:
  rollbackLimit: 1
  forProvider:
    chart:
      name: generic-deployment
      repository: https://johnathan-sq.github.io/charts/
      version: "0.2.0"
    namespace: wordpress-4
    wait: true
    waitTimeout: 15s
    values:
      replicaCount: 1
      image:
        repository: nginxx
        pullPolicy: IfNotPresent
        tag: "latest"
  providerConfigRef:
    name: helm-provider
```

Then you will see that there will be a continuous loop of rollbacks because the deployed Release doesn't match the Helm release.

### What environment did it happen in?

Crossplane version: v1.15
Provider Helm: 1.17

Unless I'm doing something wrong or have something configured incorrectly, happy to call me out.
