### ISSUE TITLE
Unable to pull charts from ghcr.io, login error

### ISSUE THREAD

**Issue by irizzant** [crossplane-contrib/provider-helm#242]
### What happened?

I think this is related to https://github.com/crossplane-contrib/provider-helm/issues/132.

I have the following Release, which uses a public ghcr.io repo
```yaml
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: test
spec:
  forProvider:
    chart:
      name: gha-runner-scale-set-controller
      repository: "oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller"
      version: 0.9.3
    namespace: arc-systems
  providerConfigRef:
    name: default
```
but when I deploy it I get this error:
```
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2024-10-22T16:38:26Z
    Reason:                Creating
    Status:                False
    Type:                  Ready
    Last Transition Time:  2024-10-22T16:38:26Z
    Message:               create failed: failed to install release: failed to pull chart: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aactions%2Factions-runner-controller-charts%2Fgha-runner-scale-set-controller%2Fgha-runner-scale-set-controller%3Apull&service=ghcr.io: 403 Forbidden
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                        Age              From                                Message
  ----     ------                        ----             ----                                -------
  Warning  CannotCreateExternalResource  6s (x7 over 8s)  managed/release.helm.crossplane.io  failed to install release: failed to pull chart: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%!A(MISSING)actions%!F(MISSING)actions-runner-controller-charts%!F(MISSING)gha-runner-scale-set-controller%!F(MISSING)gha-runner-scale-set-controller%!A(MISSING)pull&service=ghcr.io: 403 Forbidden
```

### How can we reproduce it?

* install crossplane 1.17.1
* install helm provider 0.19.0
* apply the aforementioned Release

### What environment did it happen in?
Crossplane version: 1.17.1
