### ISSUE TITLE
Skip set if valueFrom source ref is optional and missing

### ISSUE THREAD

**Issue by simonklb** [crossplane-contrib/provider-helm#265]
### What problem are you facing?

With a release spec like this:
```yaml
forProvider:
  set:
    - name: foo
      valueFrom:
        secretKeyRef:
          name: bar
          namespace: baz
          key: optionalKey
          optional: true
```

The release installation fails with `missing value for --set` if the secret is missing.

### How could Crossplane help solve your problem?

To make optional source refs useful in the context of set would it not make sense to also skip the set if the value is missing? Two possible solutions I see would be to either check if the value source is optional and skip it or introduce a way of marking a set optional as well.
