### ISSUE TITLE
Create Connection Secrets

### ISSUE THREAD

**Issue by srueg** [crossplane-contrib/provider-helm#56]
### What problem are you facing?

Currently there's no way to create a connection secret from a resource provisioned by provider-helm. For example using the [MariaDB Chart](https://github.com/bitnami/charts/tree/master/bitnami/mariadb) I'd like to expose the username, password and hostname in a connection secret.

### How could Crossplane help solve your problem?

Reading state back from created resources by a Helm chart provider-helm could create a connection secret.
Might be related to https://github.com/crossplane/crossplane/issues/1722 and/or https://github.com/crossplane/crossplane/issues/1603.

**Comment by turkenh** [comment]
This sounds like a good idea which could easily be implemented if we limit connection secret to contain only some remote secret content. This could help for syncing back `username` and `password` in the given example but not for `hostname`. 

However, to support `hostname` as well, we would need to support reading arbitrary resources back (e.g. ip of loadbalancer type service), not only secrets which would require some more work where we would need to define some API to specify which field of which resource to read and store with which key in connection secret.

Something like:

```
apiVersion: helm.crossplane.io/v1alpha1
kind: Release
metadata:
  name: mariadb-example
spec:
  connectionDetails:
    - apiVersion: v1
      kind: Secret
      name: mariadb-example
      namespace: mariadb
    - apiVersion: v1
      kind: Service
      name: mariadb-example
      namespace: mariadb
      fieldPath: status.loadBalancer.ingress[0].ip
      toConnectionSecretKey: hostname
  writeConnectionSecretToRef:
    name: mariadb-conn
    namespace: crossplane-system
  forProvider:
    ...
```
