### ISSUE TITLE
Expose Ready Condition

### ISSUE THREAD

**Issue by srueg** [crossplane-contrib/provider-helm#57]
### What problem are you facing?
Currently the `Release` CRD exposes a `Synced` condition, which does not work well with the default `readinessChecks` of a `Composition` since it's expecting a `Ready` condition instead.
A custom `readinessCheck` would be required for each `Release` in a `Composition` just to use the `Synced` string.

### How could Crossplane help solve your problem?
Either change the condition from `Synced` to `Ready` or add an additional condition of type `Ready`.

**Comment by srueg** [comment]
Ok, now I see a `Ready` condition on the `Release` status. Not sure what I observed before.

**Comment by srueg** [comment]
Seems like there is some kind of race condition which results in the `Ready` condition being skipped. It happened again:

```
k get releases.helm.crossplane.io example-mariadb-5qtrp-ptzwt -oyaml
apiVersion: helm.crossplane.io/v1alpha1
kind: Release
...
status:
  atProvider:
    releaseDescription: Install complete
    revision: 1
    state: deployed
  conditions:
  - lastTransitionTime: "2020-10-27T14:17:24Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  synced: true
```

Deleting the claim and creating again works:

```
k get releases.helm.crossplane.io example-mariadb-nfsxl-6lzfb -oyaml
apiVersion: helm.crossplane.io/v1alpha1
kind: Release
...
status:
  atProvider:
    releaseDescription: Install complete
    revision: 1
    state: deployed
  conditions:
  - lastTransitionTime: "2020-10-27T14:23:31Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-10-27T14:23:31Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  synced: true
```
