### ISSUE TITLE
Mark Created Namespaces

### ISSUE THREAD

**Issue by srueg** [crossplane-contrib/provider-helm#77]
### What problem are you facing?

If a chart is uninstalled, the previously created namespace won't be deleted with it. This might be a good thing because other resources like PVCs are also left in place (if they're created by a StatefulSet for example).
Nevertheless we want to remove these orphaned namespaces at some point.

### How could Crossplane help solve your problem?

If a release was deleted and the chart was successfully uninstalled, the provider could add a label & annotation to the namespace:
```yaml
metadata:
  labels:
    meta.helm.sh/deleted: 'true'
  annotations:
    meta.helm.sh/deletionTimestamp: "2021-01-18T13:25:35Z"
```

This would help to manually or automatically remove namespaces of uninstalled charts:
```
kubectl delete ns -l meta.helm.sh/deleted=true
```
