### ISSUE TITLE
Getting connection detail from manually generated secret

### ISSUE THREAD

**Issue by limejuly** [crossplane-contrib/provider-helm#99]
### What problem are you facing?

I can reference a secret that is generated by provider-helm, like the following example sited from [example](https://github.com/crossplane-contrib/provider-helm/blob/master/examples/sample/release.yaml). But if that secret is generated manually, it can't be referenced, the generated credential would be empty. 
``` yaml
    - apiVersion: v1
      kind: Secret
      name: wordpress-example
      namespace: crossplane-svc
      fieldPath: data.wordpress-password
      toConnectionSecretKey: password
```

### How could Crossplane help solve your problem?

Is there any chance we can reference secrets that are not generated by provider-helm? (or any workarounds?) There's scenarios where we have to generate certs manually, and deliver it to end application via crossplane. Thanks!
